:- module(class_options, []).

:- use_module(u(ur_option)).
:- use_module(library(clpfd)).

setup_options :-

   ur_options(class_diagram:class_diagram,
              [[option(is_primary/1), default(is_primary(_))],
               [option(only_class/1), default(only_class(_))]
              ]),
   ur_options(object_v:nonneg_set_gen,
              [[option(range/2), default(range(1, 100000))],
               [meta_option(generator/1),
                default(generator(randgen:lcq_gnu))],
               [option(seed/1), default(seed(-1))]
              ]),
   ur_options(http_request_v:http_method_set_gen,
              [[multi_group(http_method_type),
                option(http_method_standard/0),
                option(http_method_extension/0),
                default([http_method_standard])],
               [option(length/2), default(length(1, 100))],
               [meta_option(generator/1),
                default(generator(randgen:lcq_gnu))],
               [option(seed/1), default(seed(-1))]
              ]),
   ur_options(gt_strings:random_string,
              [[group(det), option(semidet/0), option(nondet/0)],
               [multi_group(length), %not_empty,
                option(empty/0), option(length/1), option(length/2),
                default([empty, length(1, 80)])],
               [multi_group(pattern),
                option(regex/1),
                option(range/1),
                meta_option(pattern/1),
                option(static/1),
                default([range(32..126)])],
               [meta_option(generator/1),
                default(generator(randgen:lcq_gnu))],
               [group(seed), option(seed/1), option(seed/2), default(seed(-1))]
              ]),
   ur_options(gt_numbers:random_number,
              [[multi_group(domain), 
                option(integer/0), option(rational/0), option(real/0),
                default([integer])],
               [multi_group(pattern),
                option(range/1),
                meta_option(pattern/1),
                default([range(-100..100)])],
               [meta_option(generator/1),
                default(generator(randgen:lcq_gnu))],
               [group(seed),
                option(seed/1), option(seed/2), 
                default(seed(-1))]
              ]),
   ur_options(ixpath:ixpath,
              [[group(v),
                option(v/0),
                option(vx/0), option(vix/0), option(vixc/0)]]),
   ur_options(global:simple_value_type,
              [[multi_group(list),
                option(quotedstring/0),
                option(date/0),
                option(number/0),
                option(compound/0),
                option(recursive/0),
                option(datetime/0),
                default([quotedstring, number])]
              ]),
   ur_options(global:value_token_type,
              [[multi_group(list),
                option(simple_value/0),
                option(assignment/0),
                default([simple_value, assignment])]
              ]),
    ur_options(global:operation_type,
               [[multi_group(list),
                 option(insert/0),
                 option(update/0),
                 option(add/0),
                 option(delete/0),
                 option(truncate/0),
                 option(rename/0),
                 option(trigger/0),
                 option(validate/0),
                 option(check/0),
                 default([add])]
                ]),
    ur_options(global:item_name,
               [[multi_group(list),
                 option(ado/0), 
                 option(list/0),
                 option(derived_list/0),
                 option(list_contents/0),
                 option(curve/0),
                 option(derived_curve/0),
                 option(curve_contents/0),
                 option(ado_code_/0),
                 option(ado_attribute_/0),
                 option(interface/0),
                 option(interface_parameter/0),
                 option(interface_mapping/0),
                 option(formula/0),
                 option(calendar/0),
                 option(holiday/0),
                 option(staticattribute/0),
                 option(staticattribute_enum/0),
                 option(staticattribute_code/0),
                 option(staticattribute_dep/0),
                 option(datafileattribute/0),
                 option(datafileattribute_code/0),
                 option(tree/0),
                 option(user/0),
                 option(user_group/0),
                 option(user_role/0),
                 option(group/0),
                 option(role/0),
                 option(role_expr/0),
                 option(process/0),
                 option(process_info/0),
                 option(logging/0),
                 option(attribute_formula/0),
                 default([staticattribute%, 
                          %staticattribute_enum,
                          %staticattribute_code, 
                          %staticattribute_dep
                         ])]
                ]),
    ur_options(global:transaction_type,
               [[multi_group(list),
                 option(sql/0), option(object/0), option(proc/0),
                 default([object])]
               ]),
    ur_options(global:transaction_header_flag,
               [[multi_group(list), 
                 %TODO actually it can contains several opts.
                 option(nofail/0),
                 default([nofail])]
               ]),
    ur_options(global:values,
               [[multi_group(length),
                 option(length/1),
                 default([length(1..10)])],
                [meta_option(generator/1),
                 default(generator(randgen:lcq_gnu))],
                [group(seed),
                 option(seed/1), option(seed/2), 
                 default(seed(-1))]
               ]),
    ur_options(global:operations,
               [[multi_group(length),
                 option(length/1),
                 default([length(1..10)])],
                [meta_option(generator/1),
                 default(generator(randgen:lcq_gnu))],
                [group(seed),
                 option(seed/1), option(seed/2), 
                 default(seed(-1))]
               ]),
    ur_options(global:transaction_bodies,
               [[multi_group(length),
                 option(length/1),
                 default([length(1..3)])],
                [meta_option(generator/1),
                 default(generator(randgen:lcq_gnu))],
                [group(seed),
                 option(seed/1), option(seed/2), 
                 default(seed(-1))]
               ]),
    ur_options(global:add_operation_v, []),
    ur_options(global:assignment_v, []),
    ur_options(global:item_v, []),
    ur_options(global:name_in_assignment_v, []),
    ur_options(global:value_v, []),
    ur_options(global:values_v, []),
    ur_options(global:object_transaction_body_v, []),
    ur_options(global:operation_v, []),
    ur_options(global:operation_list_v, []),
    ur_options(global:simple_value_v, []),
    ur_options(global:transaction_v, []),
    ur_options(global:transaction_header_v, []),
    ur_options(global:transaction_body_v, []),
    ur_options(global:transaction_body_list_v, []).

:- initialization setup_options.
